### PR TITLE
Add support for PodNetworkConnectivityChecks

### PR DESCRIPTION
**Pull request by cptmorgan-rh**
PodNetworkConnectivityChecks are saved in the must-gather under `<mg.path>/pod_network_connectivity_check/podnetworkconnectivitychecks.yaml`

This adds support to `omc` by allowing you to view them by running `omc get podnetworkconnectivitychecks -n openshift-diagnostics`

```bash
$ omc get podnetworkconnectivitychecks -n openshift-network-diagnostics
NAME                                                            AGE
network-check-source-10-to-kubernetes-default-service-cluster   239d
```

### CODE REVIEW

**Comment by gmeghnag** [comment]
Hey @cptmorgan-rh thank you for the PR, I'll merge it, but I'm wondering why the `podnetworkconnectivitycheck.controlplane.operator.openshift.io` resources are not located into their namespace folder, as they should be, do you have any idea?

**Comment by cptmorgan-rh** [comment]
@gmeghnag - I am the author of the script that pulls the files in the must-gather. I can't remember why we placed them in their own folder and not in their namespace. Would have made accessing them a lot easier with `omc`.

**Comment by gmeghnag** [comment]
@cptmorgan-rh Yes, as it would not have required modifying the omc code to inspect these resources, can you modify the must-gather script so we can avoid making this change here?

**Comment by cptmorgan-rh** [comment]
The code has been there for over two years so I'm not sure they will. I can ask and let you know.

**Comment by gmeghnag** [comment]
@cptmorgan-rh did you have any chance to check it?

**Comment by cptmorgan-rh** [comment]
@gmeghnag 

Insights rules exist for the file location so we can't change it now.

**Comment by cptmorgan-rh** [comment]
@gmeghnag - I have fixed the conflicts and it's good to merge.

**Pull request merged**
